// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Habilitar.Core.Models
{
    public partial class ExercicioGrupo
    {
        public int ExercicioId { get; set; }
        public int GrupoId { get; set; }
        public string Ip { get; set; }
        public bool Ativo { get; set; } = true;
        public DateTime DataCriacao { get; set; } = DateTime.Now;
        public Guid UsuarioCriacaoId { get; set; }
        public DateTime? DataAtualizacao { get; set; }
        public Guid? UsuarioAtualizacaoId { get; set; }

        public virtual Exercicio Exercicio { get; set; }
        public virtual Grupo Grupo { get; set; }
    }
}