// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Habilitar.Core.Models
{
    public partial class ExercicioGrupo
    {
        public int ExercicioId { get; set; }
        public int GrupoId { get; set; }

        public virtual Exercicio Exercicio { get; set; }
        public virtual Grupo Grupo { get; set; }
    }
}