// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Habilitar.Core.Models
{
    public partial class LogErro
    {
        public int Id { get; set; }
        public string Erro { get; set; }
        public string Acao { get; set; }
        public string Tela { get; set; }
        public int? UsuarioId { get; set; }
        public string Ip { get; set; }
        public DateTime DataCriacao { get; set; }
    }
}