// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Habilitar.Core.Models
{
    public partial class Unidade
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public string Cnes { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public int EmpresaId { get; set; }
        public string Ip { get; set; }
        public bool Ativo { get; set; } = true;
        public DateTime DataCriacao { get; set; } = DateTime.Now;
        public Guid UsuarioCriacaoId { get; set; }
        public DateTime? DataAtualizacao { get; set; }
        public Guid? UsuarioAtualizacaoId { get; set; }

        public virtual Empresa Empresa { get; set; }
    }
}