// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Habilitar_API.Models
{
    [Index(nameof(MetricaId), Name = "IX_ExercicioMetrica_MetricaId")]
    [Index(nameof(UsuarioAtualizacaoId), Name = "IX_ExercicioMetrica_UsuarioAtualizacaoId")]
    [Index(nameof(UsuarioCriacaoId), Name = "IX_ExercicioMetrica_UsuarioCriacaoId")]
    public partial class ExercicioMetrica
    {
        [Key]
        public int ExercicioId { get; set; }
        [Key]
        public short MetricaId { get; set; }
        [Required]
        [StringLength(20)]
        public string Ip { get; set; }
        public bool Ativo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataCriacao { get; set; }
        public int UsuarioCriacaoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        public int? UsuarioAtualizacaoId { get; set; }

        [ForeignKey(nameof(ExercicioId))]
        [InverseProperty("ExercicioMetrica")]
        public virtual Exercicio Exercicio { get; set; }
        [ForeignKey(nameof(MetricaId))]
        [InverseProperty("ExercicioMetrica")]
        public virtual Metrica Metrica { get; set; }
        [ForeignKey(nameof(UsuarioAtualizacaoId))]
        [InverseProperty(nameof(Usuario.ExercicioMetricaUsuarioAtualizacao))]
        public virtual Usuario UsuarioAtualizacao { get; set; }
        [ForeignKey(nameof(UsuarioCriacaoId))]
        [InverseProperty(nameof(Usuario.ExercicioMetricaUsuarioCriacao))]
        public virtual Usuario UsuarioCriacao { get; set; }
    }
}