// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Habilitar_API.Models
{
    [Index(nameof(GrupoId), Name = "IX_ExercicioGrupo_GrupoId")]
    [Index(nameof(UsuarioAtualizacaoId), Name = "IX_ExercicioGrupo_UsuarioAtualizacaoId")]
    [Index(nameof(UsuarioCriacaoId), Name = "IX_ExercicioGrupo_UsuarioCriacaoId")]
    public partial class ExercicioGrupo
    {
        [Key]
        public int ExercicioId { get; set; }
        [Key]
        public int GrupoId { get; set; }
        [Required]
        [StringLength(20)]
        public string Ip { get; set; }
        public bool Ativo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataCriacao { get; set; }
        public int UsuarioCriacaoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        public int? UsuarioAtualizacaoId { get; set; }

        [ForeignKey(nameof(ExercicioId))]
        [InverseProperty("ExercicioGrupo")]
        public virtual Exercicio Exercicio { get; set; }
        [ForeignKey(nameof(GrupoId))]
        [InverseProperty("ExercicioGrupo")]
        public virtual Grupo Grupo { get; set; }
        [ForeignKey(nameof(UsuarioAtualizacaoId))]
        [InverseProperty(nameof(Usuario.ExercicioGrupoUsuarioAtualizacao))]
        public virtual Usuario UsuarioAtualizacao { get; set; }
        [ForeignKey(nameof(UsuarioCriacaoId))]
        [InverseProperty(nameof(Usuario.ExercicioGrupoUsuarioCriacao))]
        public virtual Usuario UsuarioCriacao { get; set; }
    }
}