// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Habilitar_API.Models
{
    [Index(nameof(UsuarioAtualizacaoId), Name = "IX_Exercicio_UsuarioAtualizacaoId")]
    [Index(nameof(UsuarioCriacaoId), Name = "IX_Exercicio_UsuarioCriacaoId")]
    public partial class Exercicio
    {
        public Exercicio()
        {
            ExercicioGrupo = new HashSet<ExercicioGrupo>();
            ExercicioMetrica = new HashSet<ExercicioMetrica>();
            Meta = new HashSet<Meta>();
            PacienteMeta = new HashSet<PacienteMeta>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string Nome { get; set; }
        [StringLength(100)]
        public string NomePopular { get; set; }
        [StringLength(100)]
        public string Descricao { get; set; }
        [StringLength(200)]
        public string Url { get; set; }
        [Required]
        [StringLength(20)]
        public string Ip { get; set; }
        public bool Ativo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataCriacao { get; set; }
        public int UsuarioCriacaoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        public int? UsuarioAtualizacaoId { get; set; }

        [ForeignKey(nameof(UsuarioAtualizacaoId))]
        [InverseProperty(nameof(Usuario.ExercicioUsuarioAtualizacao))]
        public virtual Usuario UsuarioAtualizacao { get; set; }
        [ForeignKey(nameof(UsuarioCriacaoId))]
        [InverseProperty(nameof(Usuario.ExercicioUsuarioCriacao))]
        public virtual Usuario UsuarioCriacao { get; set; }
        [InverseProperty("Exercicio")]
        public virtual ICollection<ExercicioGrupo> ExercicioGrupo { get; set; }
        [InverseProperty("Exercicio")]
        public virtual ICollection<ExercicioMetrica> ExercicioMetrica { get; set; }
        [InverseProperty("Exercicio")]
        public virtual ICollection<Meta> Meta { get; set; }
        [InverseProperty("Exercicio")]
        public virtual ICollection<PacienteMeta> PacienteMeta { get; set; }
    }
}