// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Habilitar_API.Models
{
    [Index(nameof(UsuarioAtualizacaoId), Name = "IX_Grupo_UsuarioAtualizacaoId")]
    [Index(nameof(UsuarioCriacaoId), Name = "IX_Grupo_UsuarioCriacaoId")]
    public partial class Grupo
    {
        public Grupo()
        {
            ExercicioGrupo = new HashSet<ExercicioGrupo>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string Descricao { get; set; }
        [StringLength(200)]
        public string Observacao { get; set; }
        public bool Ativo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataCriacao { get; set; }
        public int UsuarioCriacaoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        public int? UsuarioAtualizacaoId { get; set; }

        [ForeignKey(nameof(UsuarioAtualizacaoId))]
        [InverseProperty(nameof(Usuario.GrupoUsuarioAtualizacao))]
        public virtual Usuario UsuarioAtualizacao { get; set; }
        [ForeignKey(nameof(UsuarioCriacaoId))]
        [InverseProperty(nameof(Usuario.GrupoUsuarioCriacao))]
        public virtual Usuario UsuarioCriacao { get; set; }
        [InverseProperty("Grupo")]
        public virtual ICollection<ExercicioGrupo> ExercicioGrupo { get; set; }
    }
}