// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Habilitar_API.Models
{
    [Index(nameof(EmpresaId), Name = "IX_Meta_EmpresaId")]
    [Index(nameof(ExercicioId), Name = "IX_Meta_ExercicioId")]
    [Index(nameof(FisioterapeutaId), Name = "IX_Meta_FisioterapeutaId")]
    [Index(nameof(IntervaloId), Name = "IX_Meta_IntervaloId")]
    [Index(nameof(MetricaId), Name = "IX_Meta_MetricaId")]
    [Index(nameof(UsuarioAtualizacaoId), Name = "IX_Meta_UsuarioAtualizacaoId")]
    [Index(nameof(UsuarioCriacaoId), Name = "IX_Meta_UsuarioCriacaoId")]
    public partial class Meta
    {
        public Meta()
        {
            PacienteMeta = new HashSet<PacienteMeta>();
        }

        [Key]
        public int Id { get; set; }
        public int ExercicioId { get; set; }
        public int QtdSeries { get; set; }
        public short MetricaId { get; set; }
        public int MetricaQtd { get; set; }
        public short IntervaloId { get; set; }
        public int EmpresaId { get; set; }
        public int? FisioterapeutaId { get; set; }
        [Required]
        [StringLength(20)]
        public string Ip { get; set; }
        public bool Ativo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataCriacao { get; set; }
        public int UsuarioCriacaoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        public int? UsuarioAtualizacaoId { get; set; }

        [ForeignKey(nameof(EmpresaId))]
        [InverseProperty("Meta")]
        public virtual Empresa Empresa { get; set; }
        [ForeignKey(nameof(ExercicioId))]
        [InverseProperty("Meta")]
        public virtual Exercicio Exercicio { get; set; }
        [ForeignKey(nameof(FisioterapeutaId))]
        [InverseProperty(nameof(Usuario.MetaFisioterapeuta))]
        public virtual Usuario Fisioterapeuta { get; set; }
        [ForeignKey(nameof(IntervaloId))]
        [InverseProperty("Meta")]
        public virtual Intervalo Intervalo { get; set; }
        [ForeignKey(nameof(MetricaId))]
        [InverseProperty("Meta")]
        public virtual Metrica Metrica { get; set; }
        [ForeignKey(nameof(UsuarioAtualizacaoId))]
        [InverseProperty(nameof(Usuario.MetaUsuarioAtualizacao))]
        public virtual Usuario UsuarioAtualizacao { get; set; }
        [ForeignKey(nameof(UsuarioCriacaoId))]
        [InverseProperty(nameof(Usuario.MetaUsuarioCriacao))]
        public virtual Usuario UsuarioCriacao { get; set; }
        [InverseProperty("Meta")]
        public virtual ICollection<PacienteMeta> PacienteMeta { get; set; }
    }
}