// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Habilitar_API.Models
{
    [Index(nameof(UsuarioAtualizacaoId), Name = "IX_Metrica_UsuarioAtualizacaoId")]
    [Index(nameof(UsuarioCriacaoId), Name = "IX_Metrica_UsuarioCriacaoId")]
    public partial class Metrica
    {
        public Metrica()
        {
            ExercicioMetrica = new HashSet<ExercicioMetrica>();
            Meta = new HashSet<Meta>();
            PacienteMeta = new HashSet<PacienteMeta>();
        }

        [Key]
        public short Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Descricao { get; set; }
        [StringLength(5)]
        public string Sigla { get; set; }
        [StringLength(150)]
        public string Observacao { get; set; }
        public bool Ativo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataCriacao { get; set; }
        public int UsuarioCriacaoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        public int? UsuarioAtualizacaoId { get; set; }

        [ForeignKey(nameof(UsuarioAtualizacaoId))]
        [InverseProperty(nameof(Usuario.MetricaUsuarioAtualizacao))]
        public virtual Usuario UsuarioAtualizacao { get; set; }
        [ForeignKey(nameof(UsuarioCriacaoId))]
        [InverseProperty(nameof(Usuario.MetricaUsuarioCriacao))]
        public virtual Usuario UsuarioCriacao { get; set; }
        [InverseProperty("Metrica")]
        public virtual ICollection<ExercicioMetrica> ExercicioMetrica { get; set; }
        [InverseProperty("Metrica")]
        public virtual ICollection<Meta> Meta { get; set; }
        [InverseProperty("Metrica")]
        public virtual ICollection<PacienteMeta> PacienteMeta { get; set; }
    }
}