// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Habilitar_API.Models
{
    [Index(nameof(PacienteMetaId), Name = "IX_PacienteMetaDiaria_PacienteMetaId")]
    public partial class PacienteMetaDiaria
    {
        public PacienteMetaDiaria()
        {
            PacienteMetaDiariaLog = new HashSet<PacienteMetaDiariaLog>();
        }

        [Key]
        public int Id { get; set; }
        public int PacienteMetaId { get; set; }
        [Column(TypeName = "date")]
        public DateTime Data { get; set; }
        public int MetricaQtd { get; set; }
        public int? QtdRealizado { get; set; }
        [Required]
        [StringLength(20)]
        public string Ip { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }

        [ForeignKey(nameof(PacienteMetaId))]
        [InverseProperty("PacienteMetaDiaria")]
        public virtual PacienteMeta PacienteMeta { get; set; }
        [InverseProperty("PacienteMetaDiaria")]
        public virtual ICollection<PacienteMetaDiariaLog> PacienteMetaDiariaLog { get; set; }
    }
}