// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Habilitar_API.Models
{
    [Index(nameof(ExercicioId), Name = "IX_PacienteMeta_ExercicioId")]
    [Index(nameof(FisioterapeutaId), Name = "IX_PacienteMeta_FisioterapeutaId")]
    [Index(nameof(IntervaloId), Name = "IX_PacienteMeta_IntervaloId")]
    [Index(nameof(MetaId), Name = "IX_PacienteMeta_MetaId")]
    [Index(nameof(MetricaId), Name = "IX_PacienteMeta_MetricaId")]
    [Index(nameof(PessoaId), Name = "IX_PacienteMeta_PessoaId")]
    [Index(nameof(UsuarioAtualizacaoId), Name = "IX_PacienteMeta_UsuarioAtualizacaoId")]
    [Index(nameof(UsuarioCriacaoId), Name = "IX_PacienteMeta_UsuarioCriacaoId")]
    public partial class PacienteMeta
    {
        public PacienteMeta()
        {
            PacienteMetaDiaria = new HashSet<PacienteMetaDiaria>();
        }

        [Key]
        public int Id { get; set; }
        public int PessoaId { get; set; }
        public int? MetaId { get; set; }
        public int FisioterapeutaId { get; set; }
        [Column(TypeName = "date")]
        public DateTime DataInicial { get; set; }
        [Column(TypeName = "date")]
        public DateTime DataFinal { get; set; }
        public int ExercicioId { get; set; }
        public int QtdSeries { get; set; }
        public short MetricaId { get; set; }
        public int MetricaQtd { get; set; }
        public short IntervaloId { get; set; }
        public bool Domingo { get; set; }
        public bool SegundaFeira { get; set; }
        public bool TercaFeira { get; set; }
        public bool QuartaFeira { get; set; }
        public bool QuintaFeira { get; set; }
        public bool SextaFeira { get; set; }
        public bool Sabado { get; set; }
        [Required]
        [StringLength(20)]
        public string Ip { get; set; }
        public bool Ativo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataCriacao { get; set; }
        public int UsuarioCriacaoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        public int? UsuarioAtualizacaoId { get; set; }

        [ForeignKey(nameof(ExercicioId))]
        [InverseProperty("PacienteMeta")]
        public virtual Exercicio Exercicio { get; set; }
        [ForeignKey(nameof(FisioterapeutaId))]
        [InverseProperty(nameof(Usuario.PacienteMetaFisioterapeuta))]
        public virtual Usuario Fisioterapeuta { get; set; }
        [ForeignKey(nameof(IntervaloId))]
        [InverseProperty("PacienteMeta")]
        public virtual Intervalo Intervalo { get; set; }
        [ForeignKey(nameof(MetaId))]
        [InverseProperty("PacienteMeta")]
        public virtual Meta Meta { get; set; }
        [ForeignKey(nameof(MetricaId))]
        [InverseProperty("PacienteMeta")]
        public virtual Metrica Metrica { get; set; }
        [ForeignKey(nameof(PessoaId))]
        [InverseProperty("PacienteMeta")]
        public virtual Pessoa Pessoa { get; set; }
        [ForeignKey(nameof(UsuarioAtualizacaoId))]
        [InverseProperty(nameof(Usuario.PacienteMetaUsuarioAtualizacao))]
        public virtual Usuario UsuarioAtualizacao { get; set; }
        [ForeignKey(nameof(UsuarioCriacaoId))]
        [InverseProperty(nameof(Usuario.PacienteMetaUsuarioCriacao))]
        public virtual Usuario UsuarioCriacao { get; set; }
        [InverseProperty("PacienteMeta")]
        public virtual ICollection<PacienteMetaDiaria> PacienteMetaDiaria { get; set; }
    }
}