// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Habilitar_API.Models
{
    [Index(nameof(PacienteMetaDiariaId), Name = "IX_PacienteMetaDiariaLog_PacienteMetaDiariaId")]
    public partial class PacienteMetaDiariaLog
    {
        [Key]
        public int Id { get; set; }
        public int PacienteMetaDiariaId { get; set; }
        public int QtdRealizado { get; set; }
        [Required]
        [StringLength(20)]
        public string Ip { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataCriacao { get; set; }

        [ForeignKey(nameof(PacienteMetaDiariaId))]
        [InverseProperty("PacienteMetaDiariaLog")]
        public virtual PacienteMetaDiaria PacienteMetaDiaria { get; set; }
    }
}