// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Habilitar_API.Models
{
    [Index(nameof(FuncaoId), Name = "IX_PerfilFuncao_FuncaoId")]
    [Index(nameof(UsuarioCriacaoId), Name = "IX_PerfilFuncao_UsuarioCriacaoId")]
    public partial class PerfilFuncao
    {
        [Key]
        public int PerfilId { get; set; }
        [Key]
        public int FuncaoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataCriacao { get; set; }
        public int UsuarioCriacaoId { get; set; }

        [ForeignKey(nameof(FuncaoId))]
        [InverseProperty("PerfilFuncao")]
        public virtual Funcao Funcao { get; set; }
        [ForeignKey(nameof(PerfilId))]
        [InverseProperty("PerfilFuncao")]
        public virtual Perfil Perfil { get; set; }
        [ForeignKey(nameof(UsuarioCriacaoId))]
        [InverseProperty(nameof(Usuario.PerfilFuncao))]
        public virtual Usuario UsuarioCriacao { get; set; }
    }
}