// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Habilitar_API.Models
{
    [Index(nameof(UsuarioAtualizacaoId), Name = "IX_Pessoa_UsuarioAtualizacaoId")]
    [Index(nameof(UsuarioCriacaoId), Name = "IX_Pessoa_UsuarioCriacaoId")]
    public partial class Pessoa
    {
        public Pessoa()
        {
            PacienteMeta = new HashSet<PacienteMeta>();
            Usuario = new HashSet<Usuario>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Nome { get; set; }
        [Required]
        [StringLength(50)]
        public string Sobrenome { get; set; }
        [Column(TypeName = "date")]
        public DateTime DataNascimento { get; set; }
        [Required]
        [StringLength(1)]
        public string Sexo { get; set; }
        [Required]
        [StringLength(11)]
        public string Cpf { get; set; }
        [Required]
        [StringLength(11)]
        public string Telefone { get; set; }
        [StringLength(30)]
        public string IntegracaoId { get; set; }
        [Required]
        [StringLength(50)]
        public string Email { get; set; }
        [Required]
        [StringLength(20)]
        public string Ip { get; set; }
        public bool Ativo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataCriacao { get; set; }
        public int UsuarioCriacaoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        public int? UsuarioAtualizacaoId { get; set; }

        [ForeignKey(nameof(UsuarioAtualizacaoId))]
        [InverseProperty("PessoaUsuarioAtualizacao")]
        public virtual Usuario UsuarioAtualizacao { get; set; }
        [ForeignKey(nameof(UsuarioCriacaoId))]
        [InverseProperty("PessoaUsuarioCriacao")]
        public virtual Usuario UsuarioCriacao { get; set; }
        [InverseProperty("Pessoa")]
        public virtual ICollection<PacienteMeta> PacienteMeta { get; set; }
        [InverseProperty("Pessoa")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}