// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Habilitar_API.Models
{
    [Index(nameof(EmpresaId), Name = "IX_Unidade_EmpresaId")]
    [Index(nameof(UsuarioAtualizacaoId), Name = "IX_Unidade_UsuarioAtualizacaoId")]
    [Index(nameof(UsuarioCriacaoId), Name = "IX_Unidade_UsuarioCriacaoId")]
    public partial class Unidade
    {
        public Unidade()
        {
            Usuario = new HashSet<Usuario>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(150)]
        public string Nome { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        [Required]
        [StringLength(11)]
        public string Telefone { get; set; }
        [StringLength(20)]
        public string Cnes { get; set; }
        [StringLength(50)]
        public string Latitude { get; set; }
        [StringLength(50)]
        public string Longitude { get; set; }
        public int EmpresaId { get; set; }
        [Required]
        [StringLength(20)]
        public string Ip { get; set; }
        public bool Ativo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataCriacao { get; set; }
        public int UsuarioCriacaoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        public int? UsuarioAtualizacaoId { get; set; }

        [ForeignKey(nameof(EmpresaId))]
        [InverseProperty("Unidade")]
        public virtual Empresa Empresa { get; set; }
        [ForeignKey(nameof(UsuarioAtualizacaoId))]
        [InverseProperty("UnidadeUsuarioAtualizacao")]
        public virtual Usuario UsuarioAtualizacao { get; set; }
        [ForeignKey(nameof(UsuarioCriacaoId))]
        [InverseProperty("UnidadeUsuarioCriacao")]
        public virtual Usuario UsuarioCriacao { get; set; }
        [InverseProperty("Unidade")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}