// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Habilitar_API.Models
{
    [Index(nameof(PerfilId), Name = "IX_UsuarioPerfil_PerfilId")]
    [Index(nameof(UsuarioCriacaoId), Name = "IX_UsuarioPerfil_UsuarioCriacaoId")]
    public partial class UsuarioPerfil
    {
        [Key]
        public int UsuarioId { get; set; }
        [Key]
        public int PerfilId { get; set; }
        [Required]
        [StringLength(20)]
        public string Ip { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataCriacao { get; set; }
        public int UsuarioCriacaoId { get; set; }

        [ForeignKey(nameof(PerfilId))]
        [InverseProperty("UsuarioPerfil")]
        public virtual Perfil Perfil { get; set; }
        [ForeignKey(nameof(UsuarioId))]
        [InverseProperty("UsuarioPerfilUsuario")]
        public virtual Usuario Usuario { get; set; }
        [ForeignKey(nameof(UsuarioCriacaoId))]
        [InverseProperty("UsuarioPerfilUsuarioCriacao")]
        public virtual Usuario UsuarioCriacao { get; set; }
    }
}