// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Habilitar_API.Models
{
    [Index(nameof(PessoaId), Name = "IX_Usuario_PessoaId")]
    [Index(nameof(UnidadeId), Name = "IX_Usuario_UnidadeId")]
    public partial class Usuario
    {
        public Usuario()
        {
            EmpresaUsuarioAtualizacao = new HashSet<Empresa>();
            EmpresaUsuarioCriacao = new HashSet<Empresa>();
            ExercicioGrupoUsuarioAtualizacao = new HashSet<ExercicioGrupo>();
            ExercicioGrupoUsuarioCriacao = new HashSet<ExercicioGrupo>();
            ExercicioMetricaUsuarioAtualizacao = new HashSet<ExercicioMetrica>();
            ExercicioMetricaUsuarioCriacao = new HashSet<ExercicioMetrica>();
            ExercicioUsuarioAtualizacao = new HashSet<Exercicio>();
            ExercicioUsuarioCriacao = new HashSet<Exercicio>();
            FuncaoUsuarioAtualizacao = new HashSet<Funcao>();
            FuncaoUsuarioCriacao = new HashSet<Funcao>();
            GrupoUsuarioAtualizacao = new HashSet<Grupo>();
            GrupoUsuarioCriacao = new HashSet<Grupo>();
            IntervaloUsuarioAtualizacao = new HashSet<Intervalo>();
            IntervaloUsuarioCriacao = new HashSet<Intervalo>();
            LogAcesso = new HashSet<LogAcesso>();
            LogErro = new HashSet<LogErro>();
            MetaFisioterapeuta = new HashSet<Meta>();
            MetaUsuarioAtualizacao = new HashSet<Meta>();
            MetaUsuarioCriacao = new HashSet<Meta>();
            MetricaUsuarioAtualizacao = new HashSet<Metrica>();
            MetricaUsuarioCriacao = new HashSet<Metrica>();
            PacienteMetaFisioterapeuta = new HashSet<PacienteMeta>();
            PacienteMetaUsuarioAtualizacao = new HashSet<PacienteMeta>();
            PacienteMetaUsuarioCriacao = new HashSet<PacienteMeta>();
            PerfilFuncao = new HashSet<PerfilFuncao>();
            PerfilUsuarioAtualizacao = new HashSet<Perfil>();
            PerfilUsuarioCriacao = new HashSet<Perfil>();
            PessoaUsuarioAtualizacao = new HashSet<Pessoa>();
            PessoaUsuarioCriacao = new HashSet<Pessoa>();
            UnidadeUsuarioAtualizacao = new HashSet<Unidade>();
            UnidadeUsuarioCriacao = new HashSet<Unidade>();
            UsuarioPerfilUsuario = new HashSet<UsuarioPerfil>();
            UsuarioPerfilUsuarioCriacao = new HashSet<UsuarioPerfil>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(20)]
        public string Login { get; set; }
        [Required]
        [StringLength(20)]
        public string Senha { get; set; }
        public int? PessoaId { get; set; }
        public int? UnidadeId { get; set; }
        public bool Profissional { get; set; }
        public bool Fisioterapeuta { get; set; }
        [StringLength(20)]
        public string Conselho { get; set; }
        [Required]
        [StringLength(20)]
        public string Ip { get; set; }
        public bool Ativo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataCriacao { get; set; }
        public int UsuarioCriacaoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        public int? UsuarioAtualizacaoId { get; set; }

        [ForeignKey(nameof(PessoaId))]
        [InverseProperty("Usuario")]
        public virtual Pessoa Pessoa { get; set; }
        [ForeignKey(nameof(UnidadeId))]
        [InverseProperty("Usuario")]
        public virtual Unidade Unidade { get; set; }
        [InverseProperty(nameof(Empresa.UsuarioAtualizacao))]
        public virtual ICollection<Empresa> EmpresaUsuarioAtualizacao { get; set; }
        [InverseProperty(nameof(Empresa.UsuarioCriacao))]
        public virtual ICollection<Empresa> EmpresaUsuarioCriacao { get; set; }
        [InverseProperty(nameof(ExercicioGrupo.UsuarioAtualizacao))]
        public virtual ICollection<ExercicioGrupo> ExercicioGrupoUsuarioAtualizacao { get; set; }
        [InverseProperty(nameof(ExercicioGrupo.UsuarioCriacao))]
        public virtual ICollection<ExercicioGrupo> ExercicioGrupoUsuarioCriacao { get; set; }
        [InverseProperty(nameof(ExercicioMetrica.UsuarioAtualizacao))]
        public virtual ICollection<ExercicioMetrica> ExercicioMetricaUsuarioAtualizacao { get; set; }
        [InverseProperty(nameof(ExercicioMetrica.UsuarioCriacao))]
        public virtual ICollection<ExercicioMetrica> ExercicioMetricaUsuarioCriacao { get; set; }
        [InverseProperty(nameof(Exercicio.UsuarioAtualizacao))]
        public virtual ICollection<Exercicio> ExercicioUsuarioAtualizacao { get; set; }
        [InverseProperty(nameof(Exercicio.UsuarioCriacao))]
        public virtual ICollection<Exercicio> ExercicioUsuarioCriacao { get; set; }
        [InverseProperty(nameof(Funcao.UsuarioAtualizacao))]
        public virtual ICollection<Funcao> FuncaoUsuarioAtualizacao { get; set; }
        [InverseProperty(nameof(Funcao.UsuarioCriacao))]
        public virtual ICollection<Funcao> FuncaoUsuarioCriacao { get; set; }
        [InverseProperty(nameof(Grupo.UsuarioAtualizacao))]
        public virtual ICollection<Grupo> GrupoUsuarioAtualizacao { get; set; }
        [InverseProperty(nameof(Grupo.UsuarioCriacao))]
        public virtual ICollection<Grupo> GrupoUsuarioCriacao { get; set; }
        [InverseProperty(nameof(Intervalo.UsuarioAtualizacao))]
        public virtual ICollection<Intervalo> IntervaloUsuarioAtualizacao { get; set; }
        [InverseProperty(nameof(Intervalo.UsuarioCriacao))]
        public virtual ICollection<Intervalo> IntervaloUsuarioCriacao { get; set; }
        [InverseProperty("Usuario")]
        public virtual ICollection<LogAcesso> LogAcesso { get; set; }
        [InverseProperty("Usuario")]
        public virtual ICollection<LogErro> LogErro { get; set; }
        [InverseProperty(nameof(Meta.Fisioterapeuta))]
        public virtual ICollection<Meta> MetaFisioterapeuta { get; set; }
        [InverseProperty(nameof(Meta.UsuarioAtualizacao))]
        public virtual ICollection<Meta> MetaUsuarioAtualizacao { get; set; }
        [InverseProperty(nameof(Meta.UsuarioCriacao))]
        public virtual ICollection<Meta> MetaUsuarioCriacao { get; set; }
        [InverseProperty(nameof(Metrica.UsuarioAtualizacao))]
        public virtual ICollection<Metrica> MetricaUsuarioAtualizacao { get; set; }
        [InverseProperty(nameof(Metrica.UsuarioCriacao))]
        public virtual ICollection<Metrica> MetricaUsuarioCriacao { get; set; }
        [InverseProperty(nameof(PacienteMeta.Fisioterapeuta))]
        public virtual ICollection<PacienteMeta> PacienteMetaFisioterapeuta { get; set; }
        [InverseProperty(nameof(PacienteMeta.UsuarioAtualizacao))]
        public virtual ICollection<PacienteMeta> PacienteMetaUsuarioAtualizacao { get; set; }
        [InverseProperty(nameof(PacienteMeta.UsuarioCriacao))]
        public virtual ICollection<PacienteMeta> PacienteMetaUsuarioCriacao { get; set; }
        [InverseProperty("UsuarioCriacao")]
        public virtual ICollection<PerfilFuncao> PerfilFuncao { get; set; }
        [InverseProperty(nameof(Perfil.UsuarioAtualizacao))]
        public virtual ICollection<Perfil> PerfilUsuarioAtualizacao { get; set; }
        [InverseProperty(nameof(Perfil.UsuarioCriacao))]
        public virtual ICollection<Perfil> PerfilUsuarioCriacao { get; set; }
        [InverseProperty("UsuarioAtualizacao")]
        public virtual ICollection<Pessoa> PessoaUsuarioAtualizacao { get; set; }
        [InverseProperty("UsuarioCriacao")]
        public virtual ICollection<Pessoa> PessoaUsuarioCriacao { get; set; }
        [InverseProperty("UsuarioAtualizacao")]
        public virtual ICollection<Unidade> UnidadeUsuarioAtualizacao { get; set; }
        [InverseProperty("UsuarioCriacao")]
        public virtual ICollection<Unidade> UnidadeUsuarioCriacao { get; set; }
        [InverseProperty(nameof(UsuarioPerfil.Usuario))]
        public virtual ICollection<UsuarioPerfil> UsuarioPerfilUsuario { get; set; }
        [InverseProperty(nameof(UsuarioPerfil.UsuarioCriacao))]
        public virtual ICollection<UsuarioPerfil> UsuarioPerfilUsuarioCriacao { get; set; }
    }
}