// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Habilitar_API.Models
{
    public partial class Metrica
    {
        public Metrica()
        {
            ExercicioMetrica = new HashSet<ExercicioMetrica>();
            Meta = new HashSet<Meta>();
            PacienteMeta = new HashSet<PacienteMeta>();
        }

        public short Id { get; set; }
        public string Descricao { get; set; }
        public string Sigla { get; set; }
        public string Observacao { get; set; }
        public bool Ativo { get; set; }
        public DateTime DataCriacao { get; set; }
        public int UsuarioCriacaoId { get; set; }
        public DateTime? DataAtualizacao { get; set; }
        public int? UsuarioAtualizacaoId { get; set; }

        public virtual Usuario UsuarioAtualizacao { get; set; }
        public virtual Usuario UsuarioCriacao { get; set; }
        public virtual ICollection<ExercicioMetrica> ExercicioMetrica { get; set; }
        public virtual ICollection<Meta> Meta { get; set; }
        public virtual ICollection<PacienteMeta> PacienteMeta { get; set; }
    }
}