// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Habilitar_API.Models
{
    public partial class Pessoa
    {
        public Pessoa()
        {
            PacienteMeta = new HashSet<PacienteMeta>();
            Usuario = new HashSet<Usuario>();
        }

        public int Id { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public DateTime DataNascimento { get; set; }
        public string Sexo { get; set; }
        public string Cpf { get; set; }
        public string Telefone { get; set; }
        public string IntegracaoId { get; set; }
        public string Email { get; set; }
        public string Ip { get; set; }
        public bool Ativo { get; set; }
        public DateTime DataCriacao { get; set; }
        public int UsuarioCriacaoId { get; set; }
        public DateTime? DataAtualizacao { get; set; }
        public int? UsuarioAtualizacaoId { get; set; }

        public virtual Usuario UsuarioAtualizacao { get; set; }
        public virtual Usuario UsuarioCriacao { get; set; }
        public virtual ICollection<PacienteMeta> PacienteMeta { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}