# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - habilitar-api-cont

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_246de01e2c93418bae893ae1b94e4180 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9fd75747992f4ec5810e794eed06a974 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_246de01e2c93418bae893ae1b94e4180 }}/jeffersonneto/habilitar-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'habilitar-api-cont'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d50213d254be455f9ea8683fb0753aef }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_246de01e2c93418bae893ae1b94e4180 }}/jeffersonneto/habilitar-api:${{ github.sha }}'